### ISSUE TITLE
Trouble cloning neuroethology/Util as MARS submodule

### ISSUE THREAD

**Issue by neven-x** [neuroethology/MARS#14]
Hello, I'm trying to install MARS on Windows. The main MARS repo clones just fine, but git cannot find the neuroethology/Util repo as a submodule and indeed I cannot see it on Github. Has this repo been moved/renamed?
Thank you for your help.

**Comment by annkennedy** [comment]
Apologies, the module was still Private- you should be able to find it now!

**Comment by neven-x** [comment]
Thanks!
