### ISSUE TITLE
Error when running python MARS.py

### ISSUE THREAD

**Issue by neven-x** [neuroethology/MARS#15]
Hello again, I've installed MARS and tried to run the MARS.py script. In the first instance I get a missing dependency error:

Traceback (most recent call last):
  File "MARS.py", line 32, in <module>
    from MARS_gui import *
  File "C:\Users\analysis\MARS\mars_v1_8\MARS_gui.py", line 2, in <module>
    import PySide2
ModuleNotFoundError: No module named 'PySide2'

After manually installing PySide2 (v5.12.2) via pip install I now get the following error:

Traceback (most recent call last):
  File "MARS.py", line 32, in <module>
    from MARS_gui import *
  File "C:\Users\analysis\MARS\mars_v1_8\MARS_gui.py", line 3, in <module>
    from PySide2 import QtCore
  File "C:\Users\analysis\Anaconda3\envs\mars\lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified procedure could not be found.

I'm not sure how to proceed? Thanks.

**Comment by neven-x** [comment]
For clarification this is on Windows 10 in a MARS dedicated conda environment. I have a suspicion it might be linked to CUDA or finding the cuDNN library.

**Comment by daverumph** [comment]
It looks like your system can't find the Qt DLLs.  There is a problem with the PySide2 install.  If you're not familiar with Qt and PySide2, Qt (the UI code) is implemented in C, and PySide2 provides a python interface to it.  So for it all to run, Python needs to be able to find and load the Qt DLLs.  It may be that the LD_LIBRARY_PATH environment variable isn't updated to include the directory where the DLLs were installed.

We're working to update the Windows version of MARS to include the correct version of PySide2.

**Comment by daverumph** [comment]
There is a known problem with PySide2 running on Python 3.8.0.  That version of Python has a missing symbol, causing DLL loads to fail.  Python 3.8.1 fixes the problem.

**Comment by annkennedy** [comment]
Also PySide2 should've been in the .yml file for the Windows environment, so apologies for that omission. I've committed a new version of the environment that should now work out of the box (at least it does for me on Windows 10) - let us know if that addresses the problem. And thank you for your patience!

**Comment by neven-x** [comment]
Thanks ! That works now.
