### ISSUE TITLE
No output for a long time

### ISSUE THREAD

**Issue by EBGU** [neuroethology/MARS#26]
Hi!

I found your MARS very useful!
However, after I install this package and test with my video(or sample videos), I could not get any output. The memory usage of my GPU(RTX 3090) increased to around 17GB after 20 min, possibly indicating its working.
The output on my console is the following and never changed.

python MARS.py
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1123, resource id: 14681116, major code: 40 (TranslateCoords), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 2876, resource id: 14681141, major code: 40 (TranslateCoords), minor code: 0
1 - Extracting pose
    creating the movie reader...
   Processing video for detection and pose ...
      Creating pool...
      Pool created with 8 workers. 
      Creating queues
      Queues created. 
      Linking pools
      Pools linked.
      Feeding data...
Pose   0% -- frame 0/5400 [Elapsed Time: 0:00:00] |                                   | (ETA:  --:--:--) 

Thank you very much!

BTW, this package would get an error when using two GPUs while one is out of date. The solution is here: https://github.com/tensorflow/tensorflow/issues/32793#issuecomment-585259093

**Comment by EBGU** [comment]
It outputs my result after 35min. My video is only 5400 frames of 224*224. Could there be anything wrong with my environment? It looks a bit slower than I thought.

**Comment by annkennedy** [comment]
Hi @EBGU , thanks for your comment! 35 minutes for 5400 frames of that size is definitely more time than it should take. The 20 minutes startup time is also suspicious. The first thing I always check is that tensorflow is using the GPU- it sounds like yours probably is, but could you post the output of `conda list` to confirm that tensorflow-gpu is installed?

What format are your movies in- would you be willing to send one (to ann.kennedy AT northwestern.edu) that I could test on our local copy of MARS?

**Comment by annkennedy** [comment]
Closing this issue due to a lack of response, however the most likely explanation is that tensorflow is not using the GPU. Please feel free to re-open and comment if you are still experiencing this issue- it is unfortunately a pretty common problem for ML code.
