### ISSUE TITLE
local variable 'classifier_path' referenced before assignment

### ISSUE THREAD

**Issue by TN-Huang** [neuroethology/MARS#28]
Hi! Ann

I found maybe MARS useful for our experiments!
Then I install this package and test with sample videos, but I could not classification. 

The command prompt show below:

I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
1 - Extracting pose
    creating the movie reader...
   Processing video for detection and pose ...
      Creating pool...
      Pool created with 8 workers.
      Creating queues
      Queues created.
      Linking pools
      Pools linked.
      Feeding data...
      Pools Started...9/1056 [Elapsed Time: 0:03:19] |###### | (ETA:  0:00:03)
Pose 100% -- frame 1056/1056 [Elapsed Time: 0:03:21] |#######| (Time: 0:03:21)
      Pools Finished.
      Saving...
Saved.
Pose Extracted
Feats frame 1055/1055  100% --  [Elapsed Time: 0:01:06] |####| (Time: 0:01:06)
WinFeats 100% -- Feature 262/262 [Elapsed Time: 0:00:00] |###| (Time: 0:00:00)
[DONE] top  1.22 mins
local variable 'classifier_path' referenced before assignment
Thread features done
Queue ended

I think something wrong in the "classifier_path"

Thank you very much!

**Comment by hrrh425** [comment]
Hello, I am having the same issue. Were you ever able to find a solution? 
Thanks

**Comment by annkennedy** [comment]
Thanks for noting this- I committed a bug fix that should address the problem!
