### ISSUE TITLE
MARS GUI not recognizing .mp4 or .avi file types

### ISSUE THREAD

**Issue by PhineusGage** [neuroethology/MARS#29]
Hello,

Whenever I open the MARS GUI and try to select video files for it to analyze, the program doesn't recognize my videos. I have tried both .mp4 and .avi file types with the same result. What can I change to get MARS to recognize my files?

Thank you

**Comment by annkennedy** [comment]
One likely explanation is that MARS currently looks for files whose filename ends in "_Top" (this is a bit outdated and we'll remove it in a future update.) If you add "_Top to the end of your filenames, does that fix the issue?

**Comment by PhineusGage** [comment]
All of the videos that I have been testing end in "-Top"

**Comment by annkennedy** [comment]
Can you change that dash ("-") to an underscore ("_") to see if that fixes it?

**Comment by PhineusGage** [comment]
I'm having this issue with my files ending with "_Top "

**Comment by annkennedy** [comment]
It's possible something else in the filename is causing MARS to exclude it- could you provide the full path to an example file you'd like to process with MARS?

**Comment by PhineusGage** [comment]
Of course,

D:\Michael_temp\MARS test videos\11102021_MARS_test_Top

**Comment by annkennedy** [comment]
This is probably the fault of some old video filtering code we used during development. Try pulling the fix-MARS_output_format branch of the repository and see if that fixes it?

**Comment by PhineusGage** [comment]
Unfortunately, I'm having the same issue after pulling the fix-MARS_output_format branch

**Comment by annkennedy** [comment]
Sorry for the silence, and that you're still having issues. Could you post for me your OS/version, and whether you're running MARS from the gui or with the MARS.run_mars() command in Python?

As a sanity check, could you also download the sample_videos.zip folder from https://data.caltech.edu/records/1655 and let me know if you're able to run MARS on those videos?

**Comment by PhineusGage** [comment]
Not a problem! I am focusing on getting the GUI to work right now, I'm having a separate set of issues getting the MARS.run_mars() command to work. I am running on Windows 10 pro, version 21H1. I downloaded the sample videos and had the same issue with MARS not finding the videos after navigating to the right file.

**Comment by annkennedy** [comment]
Interesting. In the gui, are you hitting the "enqueue" button after navigating to the videos, and checking the "top" and "pose" boxes before clicking the "run MARS" button?

**Comment by hrrh425** [comment]
Hello, Sorry about not replying sooner. To be honest, I think that I was forgetting to hit enqueue. That fixed my issue with file recognition. Thanks!

**Comment by annkennedy** [comment]
Ah, great! I admit the enqueue button is a little cryptic, we should try to make that clearer. Glad it's working for you now.
