### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by ycwei0321** [neuroethology/MARS#31]
Hello, I'm run MARS on windows. It has an error called winWError 2, as shown below. How can I fix it? Thanks.

Pose Extracted
Feats frame 1055/1055  100% --  [Elapsed Time: 0:01:45] |####| (Time: 0:01:45)
WinFeats 100% -- Feature 262/262 [Elapsed Time: 0:00:00] |###| (Time: 0:00:00)
[DONE] top  2.03 mins
loading top features
Thread features done
predicting labels
predicting probabilities
############################## closeinvestigation #########################
Transforming features...
Predicting...
Classifier prediction took 0.10 secs
############################## mount #########################
Transforming features...
Predicting...
Classifier prediction took 0.06 secs
############################## attack #########################
Transforming features...
Predicting...
Classifier prediction took 0.06 secs
assigning labels
Thread actions done
[WinError 2] The system cannot find the file specified      | (ETA:  --:--:--)

**Comment by annkennedy** [comment]
Thank you for bringing this to our attention! It looks like a package was missing from the MARS conda environment, that was causing the Save Video function to fail.

We have updated the `MARS_environment_windows.yml` environment file, and also repaired some display issues with the Save Video code, and merged these updates into the master branch of the repository. Could you please pull the latest version of the master branch, rebuild the conda environment, and try again?

(If you are familiar with conda and don't want to re-build the MARS conda environment, another option is to activate the existing environment and call `conda install ffmpeg` to add the missing package.)

**Comment by ycwei0321** [comment]
Great. It works. I just call "conda install ffmpeg" in conda. It seems it's much easier than to rebuild the conda environment. Thanks for your answer and work.

**Comment by annkennedy** [comment]
Excellent, thank you for confirming! Closing issue.
