### ISSUE TITLE
'MultinomialHMM' error

### ISSUE THREAD

**Issue by sshoujing** [neuroethology/MARS#36]
Hello, I'm run MARS on windows. It has an error about 'MultinomialHMM' object has no attribute 'implementation', as shown below.
How can I fix it? Thanks.

Pose Extracted
Feats frame 905/905  100% --  [Elapsed Time: 0:01:35] |######| (Time: 0:01:35)
WinFeats 100% -- Feature 262/262 [Elapsed Time: 0:00:00] |###| (Time: 0:00:00)
[DONE] top  1.84 mins
Thread features done
loading top features
predicting labels
predicting probabilities
############################## closeinvestigation #########################
Transforming features...
Predicting...
'MultinomialHMM' object has no attribute 'implementation'
'MultinomialHMM' object has no attribute 'implementation'

Are there any packages or steps i'm missing?

**Comment by Archerfaded** [comment]
Hello, I'm run MARS on windows. It has an error about 'MultinomialHMM' object has no attribute 'implementation',did you solve the problem? how to solve.

**Comment by sshoujing** [comment]
To be honest, I haven’t solved it yet.. sorry my friend

**Comment by sshoujing** [comment]
> Hello, I'm run MARS on windows. It has an error about 'MultinomialHMM' object has no attribute 'implementation',did you solve the problem? how to solve.

I installed hmmlearn version of 0.2.2, then it worked. I think you can try it.

**Comment by Archerfaded** [comment]
Could you please send me the websit or whl of hmmlearn version of 0.2.2 to me ,thanks.

2022-04-06 01:09:17sshoujing ***@***.***>写道：

Hello, I'm run MARS on windows. It has an error about 'MultinomialHMM' object has no attribute 'implementation',did you solve the problem? how to solve.

I installed hmmlearn version of 0.2.2, then it worked. I think you can try it.
