### ISSUE TITLE
MARS_1.8 GUI output for a long long time

### ISSUE THREAD

**Issue by dcwjsongweilong** [neuroethology/MARS#44]
Hi,
Thank you very much for sharing MARS!
However, after I installed this package and test with your sample videos, I get output for a long time. 
CPU(AMD R75800H) ---- GPU(RTX 3060) ----python3.7---- CUDA11.2  ---- cuDNN8.1 ----  tensorflow_GPU_2.6.0----tensorflow_2.6.0
The output on my console is the following~

D:\anaconda3\envs\mars\python.exe D:\chuan\MARS\mars_v1_8\MARS.py 
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
1 - Extracting pose
    creating the movie reader...
   Processing video for detection and pose ...
      Creating pool...
      Pool created with 8 workers.
      Creating queues
      Queues created.
      Linking pools
      Pools linked.
      Feeding data...
Pose   4% -- frame 47/1056 [Elapsed Time: 0:09:49] |         | (ETA:  3:30:56)
This really takes a long time, although using your sample_videos!

**Comment by dcwjsongweilong** [comment]
![Snipaste_08_11-35-01](https://user-images.githubusercontent.com/73086010/194686292-09fcb197-761b-4562-ade5-a5289ad17e94.jpg)
GPU occupancy is full

**Comment by dcwjsongweilong** [comment]
MARS takes three hours to process instance video (18164 frames)

1 - Extracting pose
    creating the movie reader...
   Processing video for detection and pose ...
      Creating pool...
      Pool created with 8 workers.
      Creating queues
      Queues created.
      Linking pools
      Pools linked.
      Feeding data...
      Pools Started...47/18164 [Elapsed Time: 3:24:14] |#### | (ETA:  0:00:11)
Pose 100% -- frame 18164/18164 [Elapsed Time: 3:24:20] |#####| (Time: 3:24:20)
      Pools Finished.
      Saving...
Saved.
Pose Extracted
Feats frame 18163/18163  100% --  [Elapsed Time: 0:19:16] |##| (Time: 0:19:16) 2)
WinFeats 100% -- Feature 262/262 [Elapsed Time: 0:00:01] |###| (Time: 0:00:01)
[DONE] top 19.69 mins
Thread features done
loading top features
predicting labels
predicting probabilities
############################## closeinvestigation #########################
Transforming features...
Predicting...
Classifier prediction took 1.17 secs
############################## mount #########################
Transforming features...
Predicting...
Classifier prediction took 0.96 secs
############################## attack #########################
Transforming features...
Predicting...
Classifier prediction took 0.94 secs
assigning labels
Thread actions done
qt.qpa.fonts: Unable to open default EUDC font: "EUDC.TTE"
animating8164    0% --  [Elapsed Time: 0:00:00] |           | (ETA:  --:--:--)
frame 18164/18164  100% --  [Elapsed Time: 0:33:34] |########| (Time: 0:33:34)
Thread ended

**Comment by ljwtju** [comment]
Hello, have you solved your problem? I also encountered a similar problem. When I ran MARS, the progress bar was even stuck at zero
